name: CraftPresents
version: ${project.version}
main: sp.yeyu.presents.CraftPresents
authors: [YeYu]
api-version: 1.13
description: Craft presents to your friends!
website: https://github.com/ye-yu/
commands:
  devpresent:
    description: To give an empty present
    usage: /devpresent
